### PR TITLE
Allow listening for variables outside of child

### PR DESCRIPTION
**Pull request by Immortalin**
This adds functionality to fast_ui equivalent to [ValueListenableBuilder's ValueListenable](https://api.flutter.dev/flutter/widgets/ValueListenableBuilder-class.html) and [GetX's controller's listen](https://stackoverflow.com/questions/63991803/flutter-how-to-listen-to-variable-change-on-getx).

### CODE REVIEW

**Comment by Rexios80** [comment]
I've thought about adding this field before, but if anything it will make registration more confusing. You can call `rx.register()` directly inside the closure of a `FastBuilder` if you really need to which should accomplish what you need. It's not ideal, but I know that there are some cases that automatic registration can't handle.

As for your second point... it doesn't look like you added any code for that? `fast_rx` doesn't have an equivalent to GetX controllers. If you want to directly listen to an `rx` you have access to the update `rx.stream`.

**Comment by Immortalin** [comment]
I did not add controllers, I meant they are functionally equivalent to the listen function which allows explicitly specifying reactive dependencies.

**Comment by Immortalin** [comment]
It's not more confusing, the other major frameworks have it. The confusing part is the condition callback which is not clearly documented.

**Comment by Rexios80** [comment]
Other major frameworks are verbose by design. GetX (which is what fast_rx is most heavily based on) does not have a field on `Obx` to explicitly register observables as far as I know. Adding an `observables` field would lead to duplicate registration, which could be filtered out but that's not the point. Manual registration should not be something you're doing often.

Screenshot 2023-06-14 at 7 28 01 AM

The documentation for `condition` seems pretty explicit to me if you know how widgets work. I've thought about removing that field, but that would be a breaking change so I haven't.

**Comment by Immortalin** [comment]
GetX has controllers while Fast UI does not. There is no solution to the problem of changing an observable in the parent while the child is an opaque third party widget without resorting to hacks like register.

**Comment by Rexios80** [comment]
How would a GetX controller solve this issue? That wouldn't help with registration. Explicitly calling `register` isn't a hack any more than having a field for observables to register is when that's not how fast_rx was designed to be used.

**Comment by Immortalin** [comment]
Take this example here:

https://docs.flyer.chat/flutter/chat-ui/basic-usage

We make the main widget stateless and turn the messages list into an observable. in the build function, we wrap the Chat() widget with a FastBuilder. Where do you put the register call?

**Comment by Rexios80** [comment]
I would think automatic registration would work in that case, but if it doesn't then you can just do this:

```dart
FastBuilder(() {
  messages.register();
  return Chat(messages: messages);
});
```

**Comment by Rexios80** [comment]
All automatic registration does is call register for you if any accessors get called on an observable. If registration isn't happening automatically for some reason there's no reason you can't just do it yourself.

**Comment by Immortalin** [comment]
Yes, I am surprised automatic registration didn't work. Could it be a potential bug? I published a replication [here](https://github.com/Immortalin/fast_ui_bug_replication/blob/cfd7b811fd9b9aa3370b311a0e5ac6db5404d1b6/lib/main.dart#L82). If you comment out that line, it throw the `RxObserverIsNotListenable` error claiming there are no RxValues found. 

I think the `register` function needs to be more clearly documented in the README too.

**Comment by Rexios80** [comment]
The Chat widget doesn't use the messages list early enough in the build method for it to get registered. Since you don't have control over the Chat widget, manual registration is the only option here. If you would like to draft updates to documentation you think is lacking, please go ahead and do so.

**Comment by Rexios80** [comment]
I'm going to close this PR so the history doesn't get weird. Please make a new PR with documentation updates if you do that.

**Pull request closed without merging**
